language: perl
perl:
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
sudo: false
addons:
  apt:
    packages:
    - texinfo
    - texlive
    - texi2html
install:
  - autoreconf --install
  - eval `perl -V:siteprefix`
  - ./configure --prefix=$siteprefix && make
  - make cpanm
script:
  - make distcheck
  - perl Build.PL && ./Build distcheck
