language: perl
perl:
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
sudo: false
addons:
  apt:
    packages:
    - texinfo
    - texlive
before_install:
  - cpanm -n Devel::Cover::Report::Coveralls
install:
  - autoreconf --install
  - eval `perl -V:siteprefix`
  - ./configure --prefix=$siteprefix && make
  - make cpanm
script:
  - make distcheck
  - perl Build.PL && ./Build build && cover -test -report coveralls
  - ./Build distcheck
